"""initial schema

Revision ID: a05f356fd3cc
Revises: 
Create Date: 2026-07-19 00:50:56.131431

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a05f356fd3cc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('section', sa.String(length=100), nullable=True),
    sa.Column('enrollment_status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)

    op.create_table('quiz_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.String(length=100), nullable=False),
    sa.Column('topic_id', sa.String(length=100), nullable=False),
    sa.Column('lesson_id', sa.String(length=100), nullable=False),
    sa.Column('concept_id', sa.String(length=100), nullable=False),
    sa.Column('difficulty', sa.String(length=20), nullable=False),
    sa.Column('template_id', sa.String(length=100), nullable=False),
    sa.Column('question_text', sa.String(length=1000), nullable=False),
    sa.Column('choices', sa.JSON(), nullable=False),
    sa.Column('correct_answer', sa.String(length=500), nullable=False),
    sa.Column('steps', sa.JSON(), nullable=False),
    sa.Column('answered', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('quiz_questions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quiz_questions_concept_id'), ['concept_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_quiz_questions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_quiz_questions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_quiz_questions_user_id'), ['user_id'], unique=False)

    op.create_table('quiz_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.String(length=100), nullable=False),
    sa.Column('topic_id', sa.String(length=100), nullable=False),
    sa.Column('lesson_id', sa.String(length=100), nullable=False),
    sa.Column('concept_id', sa.String(length=100), nullable=False),
    sa.Column('difficulty', sa.String(length=20), nullable=False),
    sa.Column('selected_answer', sa.String(length=500), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('elapsed_seconds', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['quiz_questions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('quiz_attempts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quiz_attempts_concept_id'), ['concept_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_quiz_attempts_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_quiz_attempts_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_quiz_attempts_question_id'), ['question_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_quiz_attempts_subject_id'), ['subject_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_quiz_attempts_topic_id'), ['topic_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_quiz_attempts_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz_attempts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quiz_attempts_user_id'))
        batch_op.drop_index(batch_op.f('ix_quiz_attempts_topic_id'))
        batch_op.drop_index(batch_op.f('ix_quiz_attempts_subject_id'))
        batch_op.drop_index(batch_op.f('ix_quiz_attempts_question_id'))
        batch_op.drop_index(batch_op.f('ix_quiz_attempts_id'))
        batch_op.drop_index(batch_op.f('ix_quiz_attempts_created_at'))
        batch_op.drop_index(batch_op.f('ix_quiz_attempts_concept_id'))

    op.drop_table('quiz_attempts')
    with op.batch_alter_table('quiz_questions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quiz_questions_user_id'))
        batch_op.drop_index(batch_op.f('ix_quiz_questions_id'))
        batch_op.drop_index(batch_op.f('ix_quiz_questions_created_at'))
        batch_op.drop_index(batch_op.f('ix_quiz_questions_concept_id'))

    op.drop_table('quiz_questions')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
